---
title: "Untitled"
output: html_document
date: "2023-03-21"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

packages <- c("rlang", "tidyverse", "tidyr", "gplots", "dplyr", "data.table", "ggplot2", "ggthemes", "stringi", "RColorBrewer","tibble", "knitr", "UpSetR", "ComplexUpset")

ipak(packages)

rm(list=ls())
dir = "C:/Users/aurel/Dropbox/Post-Doc ECLECTIC/autres projets/Aphids_TE"

```

```{r}

# data = fread(paste0(dir, "/data/MCLgroups_info_species.csv"), col.names = c("Species", "MCL", "TE_name",	"Seq_name",	"length",	"strand",	"confused",	"class",	"order",	"Wcode",	"sFamily",	"CI",	"coding",	"struct",	"other",	"MCL_group"))

better_data = fread(paste0(dir, "/data/MCL_defined_TEs_groups_by_order.csv"))
# better_data = column_to_rownames(better_data, var = "MCL_group")
better_data = better_data[1:13527,]

Aphid_species = c("DVIT", "ELAN", "RPAD", "RMAI", "AGOS", "PNIG", "SMIS", "APIS", "DNOX", "DPLA", "MPER", "MCER")


for (i in Aphid_species) {
  df = better_data %>% select("MCL_group",matches(i))
  names(df) = str_remove(names(df), pattern = paste0(i,"_"))
  df = df[,1:(ncol(df)-1)]
  
  df2 = gather(df, key = "LTR_type", value = "Number", 2:(ncol(df)))
  df2$name = paste0(df2$MCL_group, df2$LTR_type)
  names(df2)[names(df2) == 'Number'] <- i
  assign(i, df2)
}

data = full_join(AGOS, APIS) %>% full_join(DNOX) %>% full_join(DPLA) %>% full_join(DVIT) %>% full_join(ELAN) %>% full_join(MCER) %>% full_join(MPER) %>% full_join(PNIG) %>% full_join(RMAI) %>% full_join(RPAD) %>% full_join(SMIS)

data = data[,c(1,2,4,3,5:15)]
data[is.na(data)] <- 0
str(data)
data$total = rowSums(data[4:15], dims = 1)
data = filter(data, total != 0)

Aphid_species = c("DVIT", "ELAN", "RPAD", "RMAI", "AGOS", "PNIG", "SMIS", "APIS", "DNOX", "DPLA", "MPER", "MCER")
data2 <- data[, col.order]
data3 = cbind(data[,1:3], data2)

```

```{r}

ComplexUpset::upset(data3, 
                    Aphid_species,
                    min_size = 1,
                    min_degree = 2,
                    keep_empty_groups = F,
                    base_annotations=list(
                      'Intersection size'=intersection_size(
                        counts=F, 
                        mapping=aes(fill=LTR_type)
                      )
                    ),
                    width_ratio=0.1,
                    guides = 'over', 
                    sort_intersections_by='degree',
                    n_intersections = 10,
                    sort_sets = F,
)


```

